=== xoanaraujo/AD/UD2/A3p1UD2_XoanAraujoGandara/BibliotecaInformatica.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="biblioteca">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="facultad" type="xs:string"/>
                <xs:element name="Campus" type="xs:string"/>
                <xs:element name="secciones">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="seccion" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="libros">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="libro" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="autores">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="autor" type="xs:string" maxOccurs="unbounded"/>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                                <xs:element name="fechaEdicion" type="xs:string"/>
                                                                <xs:element name="editorial" type="xs:string"/>
                                                                <xs:element name="precio" type="xs:decimal"/>
                                                                <xs:element name="copias">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="copia" maxOccurs="unbounded">
                                                                                <xs:complexType>
                                                                                    <xs:attribute name="numero" type="xs:string"/>
                                                                                    <xs:attribute name="estado" type="xs:string"/>
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                            <xs:attribute name="ID" type="xs:ID" use="required"/>
                                                            <xs:attribute name="isbn" type="xs:string" use="required"/>
                                                            <xs:attribute name="titulo" type="xs:string" use="required"/>
                                                            <xs:attribute name="numero_de_paginas" type="xs:integer" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="nombre" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>

        <xs:unique name="uniqueISBN">
            <xs:selector xpath=".//libro"/>
            <xs:field xpath="@isbn"/>
        </xs:unique>
   
        <xs:unique name="uniqueNombreSeccion">
            <xs:selector xpath=".//seccion"/>
            <xs:field xpath="@nombre"/>
        </xs:unique> 
    </xs:element>
</xs:schema>

=== xoanaraujo/AD/UD2/A3p1UD2_XoanAraujoGandara/BibliotecaInformatica.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Contenido de tu documento XML -->
<biblioteca xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="BibliotecaInformatica.xsd">    

    <facultad>Informática</facultad>
    <Campus>Escuela Politécnica de Valencia </Campus>
    <secciones>
        <seccion nombre="Programación">
            <libros>
                <libro ID="A001" isbn="666-1234567890" titulo="Introducción a la Programación en Java" numero_de_paginas="300">
                    <autores>
                        <autor>John Smith</autor>
                        <autor>Maria Pérez</autor>
                        <autor>Carlos Rodríguez</autor>
                    </autores>
                    <fechaEdicion>12-12-2012</fechaEdicion>
                    <editorial>Paraninfo</editorial>
                    <precio>29</precio>
                    <copias>
                        <copia numero="1" estado="Disponible"/>
                        <copia numero="2" estado="Prestado"/>
                        <copia numero="3" estado="Disponible"/>
                    </copias>
                </libro>
                <libro ID="A002" isbn="988-1111111111" titulo="Aprende Java en 21 días" numero_de_paginas="400">
                    <autores>
                        <autor>Luis Martínez</autor>
                        <autor>John Smith</autor>
                        <autor>Maria Pérez</autor>
                    </autores>
                    <fechaEdicion>02-10-2015</fechaEdicion>
                    <editorial>Anaya Multimedias</editorial>
                    <precio>39.99</precio>
                    <copias>
                        <copia numero="1" estado="Disponible"/>
                        <copia numero="2" estado="Prestado"/>
                    </copias>
                </libro>
                <libro ID="A003" isbn="988-8822222222" titulo="Python para Principiantes" numero_de_paginas="250">
                    <autores>
                        <autor>María López</autor>
                        <autor>Carlos Rodríguez</autor>
                    </autores>
                    <fechaEdicion>02-09-2015</fechaEdicion>
                    <editorial>Coders Press</editorial>
                    <precio>24.99</precio>
                    <copias>
                        <copia numero="1" estado="Disponible"/>
                        <copia numero="2" estado="Disponible"/>
                        <copia numero="3" estado="Prestado"/>
                    </copias>
                </libro>
                <libro ID="A004" isbn="988-3633333333" titulo="Desarrollo de Aplicaciones Web con Java" numero_de_paginas="350">
                    <autores>
                        <autor>John Smith</autor>
                        <autor>Luis Martínez</autor>
                    </autores>
                    <fechaEdicion>05-03-2022</fechaEdicion>
                    <editorial>Paraninfo</editorial>
                    <precio>32.99</precio>
                    <copias>
                        <copia numero="1" estado="Disponible"/>
                        <copia numero="2" estado="Disponible"/>
                        <copia numero="3" estado="Disponible"/>
                    </copias>
                </libro>
                <libro ID="A005" isbn="968-2224444444" titulo="Programación Avanzada en Java" numero_de_paginas="280">
                    <autores>
                        <autor>Carlos Rodríguez</autor>
                        <autor>John Smith</autor>
                        <autor>Luis Martínez</autor>
                    </autores>
                    <fechaEdicion>04-10-2022</fechaEdicion>
                    <editorial>Anaya Multimedias</editorial>
                    <precio>29.99</precio>
                    <copias>
                        <copia numero="1" estado="Disponible"/>
                        <copia numero="2" estado="Prestado"/>
                        <copia numero="3" estado="Disponible"/>
                        <copia numero="4" estado="Disponible"/>
                        <copia numero="5" estado="Prestado"/>
                    </copias>
                </libro>
            </libros>
        </seccion>
        <seccion nombre="Redes">
            <libros>
                <libro ID="A101" isbn="998-5588555555" titulo="Comunicación en Redes Empresariales" numero_de_paginas="380">
                    <autores>
                        <autor>Luis Martínez</autor>
                        <autor>Maria Pérez</autor>
                    </autores>
                    <fechaEdicion>04-10-2022</fechaEdicion>
                    <editorial>Paraninfo</editorial>
                    <precio>34.99</precio>
                    <copias>
                        <copia numero="1" estado="Disponible"/>
                        <copia numero="2" estado="Prestado"/>
                        <copia numero="3" estado="Disponible"/>
                        <copia numero="4" estado="Disponible"/>
                    </copias>
                </libro>
                <libro ID="A102" isbn="878-6546666666" titulo="Seguridad en Redes Corporativas" numero_de_paginas="420">
                    <autores>
                        <autor>John Smith</autor>
                        <autor>Maria Pérez</autor>
                        <autor>Carlos Rodríguez</autor>
                    </autores>
                    <fechaEdicion>09-09-2021</fechaEdicion>
                    <editorial>Rama</editorial>
                    <precio>39.99</precio>
                    <copias>
                        <copia numero="1" estado="Disponible"/>
                        <copia numero="2" estado="Disponible"/>
                        <copia numero="3" estado="Disponible"/>
                        <copia numero="4" estado="Prestado"/>
                        <copia numero="5" estado="Disponible"/>
                    </copias>
                </libro>
                <libro ID="A103" isbn="878-8767777777" titulo="Introducción a las Redes de Comunicación" numero_de_paginas="320">
                    <autores>
                        <autor>María López</autor>
                        <autor>Carlos Rodríguez</autor>
                    </autores>
                    <fechaEdicion>14-04-2020</fechaEdicion>
                    <editorial>Anaya Multimedia</editorial>
                    <precio>29.99</precio>
                    <copias>
                        <copia numero="1" estado="Disponible"/>
                        <copia numero="2" estado="Disponible"/>
                        <copia numero="3" estado="Prestado"/>
                        <copia numero="4" estado="Disponible"/>
                    </copias>
                </libro>
                <libro ID="A104" isbn="978-8888888323" titulo="Redes Avanzadas y Protocolos de Comunicación" numero_de_paginas="350">
                    <autores>
                        <autor>John Smith</autor>
                        <autor>Luis Martínez</autor>
                        <autor>Carlos Rodríguez</autor>
                    </autores>
                    <fechaEdicion>21-12-2022</fechaEdicion>
                    <editorial>Marcombo</editorial>
                    <precio>32.00</precio>
                    <copias>
                        <copia numero="1" estado="Disponible"/>
                        <copia numero="2" estado="Prestado"/>
                        <copia numero="3" estado="Disponible"/>
                    </copias>
                </libro>
                <libro ID="A105" isbn="968-9999999543" titulo="Comunicación de Datos en Redes Empresariales" numero_de_paginas="290">
                    <autores>
                        <autor>Carlos Rodríguez</autor>
                        <autor>John Smith</autor>
                        <autor>Luis Martínez</autor>
                    </autores>
                    <fechaEdicion>04-12-2021</fechaEdicion>
                    <editorial>Paraninfo</editorial>
                    <precio>25.50</precio>
                    <copias>
                        <copia numero="1" estado="Disponible"/>
                        <copia numero="2" estado="Prestado"/>
                        <copia numero="3" estado="Disponible"/>
                        <copia numero="4" estado="Disponible"/>
                    </copias>
                </libro>
                <libro ID="A106" isbn="778-1010101032" titulo="Seguridad en Redes Empresariales" numero_de_paginas="400">
                    <autores>
                        <autor>Luis Martínez</autor>
                        <autor>Maria Pérez</autor>
                    </autores>
                    <fechaEdicion>12-03-2020</fechaEdicion>
                    <editorial>Anaya Multimedia</editorial>
                    <precio>34.5</precio>
                    <copias>
                        <copia numero="1" estado="Disponible"/>
                        <copia numero="2" estado="Prestado"/>
                        <copia numero="3" estado="Disponible"/>
                        <copia numero="4" estado="Disponible"/>
                    </copias>
                </libro>
                <libro ID="A107" isbn="343-1111114545" titulo="Introducción a la Comunicación en Redes" numero_de_paginas="350">
                    <autores>
                        <autor>María López</autor>
                        <autor>Carlos Rodríguez</autor>
                    </autores>
                    <fechaEdicion>15-07-2021</fechaEdicion>
                    <editorial>Marcombo</editorial>
                    <precio>32.99</precio>
                    <copias>
                        <copia numero="1" estado="Disponible"/>
                        <copia numero="2" estado="Prestado"/>
                        <copia numero="3" estado="Disponible"/>
                        <copia numero="4" estado="Disponible"/>
                    </copias>
                </libro>
