=== xoanaraujo/AD/UD2/A1UD2_XoanAraujoGandara/Empleados.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Empleados">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Empleado" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="Nombre"/>
                            <xs:element type="xs:string" name="Cargo"/>
                            <xs:element type="xs:string" name="Direccion"/>
                            <xs:element type="xs:string" name="Aumento"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== xoanaraujo/AD/UD2/A1UD2_XoanAraujoGandara/Empleados.xml
<?xml version="1.0" encoding="UTF-8"?>
<Empleados xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="Empleados.xsd" >
    <Empleado>
        <Nombre>Luis Pérez Esteban</Nombre>
        <Cargo>Director de Proyecto</Cargo>
        <Direccion>Sol 3, 36000 Pontevedra</Direccion>
        <Aumento>300 euros</Aumento>
    </Empleado>
    <Empleado>
        <Nombre>María Rodríguez Ramírez</Nombre>
        <Cargo>Directora de tienda</Cargo>
        <Direccion>Luna50, 36005 Pontevedra</Direccion>
        <Aumento>200 euros</Aumento>
    </Empleado>
    <Empleado>
        <Nombre>Esteban Alba Jiménez</Nombre>
        <Cargo>Gerente</Cargo>
        <Direccion>El callejón, 8 36900 Marín -Pontevedra-</Direccion>
        <Aumento>175 euros</Aumento>
    </Empleado>
</Empleados>
